version: '3.8'

services:

  mssql:
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=francis.123
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04

  EcommerceApi:
    ports:
      - 8080:80
    depends_on:
      - mssql
    image: ecommerce:v1
